# Generated by Django 3.0.4 on 2020-04-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('path', models.FilePathField(default='C:\\Users\\Arpit\\Desktop\\SDP\\Django-App(SpeakerIdentifier)\\SpeakerIdentifier\\SpeakerIdentifier\\media', path='C:\\Users\\Arpit\\Desktop\\SDP\\Django-App(SpeakerIdentifier)\\SpeakerIdentifier\\SpeakerIdentifier\\media')),
            ],
            options={
                'unique_together': {('file', 'path')},
            },
        ),
    ]
